buttons: 
  confirm-stop: 
    customId: "creonbot-confirmstop"
    label: "Подтвердить"
    style: "success"
    disabled: false 
    url: ""
    emoji: 
      enabled: true
      id: "✅"
  
  stop-attacked: 
    customId: "creonbot-stopattacked" 
    label: "Остановить атаку"
    style: "danger"
    disabled: false 
    url: ""
    emoji: 
      enabled: true
      id: "⭕"
