settings: 
  color: 
    default: "#FB00A6"
    success: "#00FBA1"
    warning: "#FB4B00"
    error: "#FB0650"
    custom: "#2f3137" 
  
  footer:
    text: "CreonDDoS"
    icon: "https://i.imgur.com/jOuUXqE.gif"

embeds: 
  error-cmd: 
    title: ""
    color: "error"
    description: 
      - "❌ ``Ошибка при выполнении команды!``"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: ""
      icon: ""
    fields: []
  
  invalid-channel: 
    title: ""
    color: "error"
    description: 
      - "❌ ``Вы не можете сделать это в этом канале!``"
      - "> Разрешенные каналы:"
      - "> {allowed_channels}"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: ""
      icon: ""
    fields: []

  cmd-disabled: 
    title: ""
    color: "error"
    description: 
      - "❌ ``Эта команда была отключена!``"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: ""
      icon: ""
    fields: []  
  
  no-perm: 
    title: ""
    color: "error"
    description: 
      - "❌ ``У вас нет разрешения на использование этой команды!``"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: ""
      icon: ""
    fields: []
  
  # Crash
  black-list-ip: 
    title: ""
    color: "error"
    description: 
      - "❌ `В настоящее время этот IP-адрес занесен в черный список!`"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: ""
      icon: ""
    fields: []
  
  invalid-verison: 
    title: ""
    color: "error"
    description: 
      - "> Версия `{version}` не найдена, пожалуйста *выберите*"
      - "> версию одну из **вариантов!**"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: ""
      icon: ""
    fields: []
  
  invalid-method: 
    title: ""
    color: "error"
    description: 
      - "> Метод с **ID** `{method}` не найден, пожалуйста"
      - "> выберите *метод* один из **вариантов!**"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: ""
      icon: ""
    fields: [] 
  
  method-disabled:  
    title: ""
    color: "error"
    description: 
      - "> __Метод__, который вы только что ввели, был"
      - "> **отключен** в конфигурации. Если вы являетесь администратором"
      - "> затем *включите его или используйте другой метод*!"
      - "```🔗 Информация```"
      - "> Метод: `{method_name}`"
      - "> ```{method_id}```"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: [] 
  
  no-role: 
    title: ""
    color: "error"
    description: 
      - "> __Метод__, который вам нужен, требует"
      - "> определенные **роли.** Которой у Вас нет!"
      - "```🔗 Информация```"
      - "> Метод: `{method_name}`"
      - "> ```{method_id}```"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: [] 
  
  send-attack: 
    title: "🚀 Атака начата"
    color: "custom"
    description: 
      - "```🔗 Информация```"
      - "> Хост: **{host}:{port}**"
      - "> Метод: **{method_name}** (`{method_id}`)"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
      - name: "🔌 __**Версия**__"
        value: "```{version} ({version_code})```"
        inline: true
      - name: "👻 __**КПС & Время**__"
        value: "```{cps} КПС | {time} Секунд```"
        inline: true
    
  attack-stopped: 
    title: "🚨 Атака была остановлена"
    color: "custom"
    description: 
      - "> __Атака__ была **остановлена**!"
      - "```🔗 Информация```"
      - "> Атака от: <@{user_id}>"
      - "> (`{user_id}`)"
    thumbnail: "{user_icon}"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "{footer_text}"
      icon: "{footer_icon}"
    fields: []

  # Stop 
  confirm-stop: 
    title: ""
    color: "custom"
    description: 
      - "> Чтобы приступить к __остановке__ атак."
      - "> Пожалуйста, **выберите** зеленую кнопку!"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: []
  
  stop-success:  
    title: "✅ Успешно остановлены"
    color: "custom"
    description: 
      - "> Один человек **выполнил** команду "stop""
      - "> Все атаки были __успешно остановлены__!"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: []
  
  # Resolver 
  checking-data: 
    title: "⌛ Запуск сканирования сервера"
    color: "custom"
    description: 
      - "> Мы __отправили__ информацию для **анализа**"
      - ">  и ждем, когда *результаты будут отправлены обратно*!"
      - "> "
      - ">  Этот процесс может *занять некоторое время*! Пожалуйста подождите :("
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
        name: "📡 __**Хост**__"
        value: "```{host}```"
        inline: true
  
  offline-host: 
    title: "🚫 Сервер недоступен"
    color: "custom"
    description: 
      - "> Мы **получили** результаты __анализа__."
      - "> Вы можете ознакомиться с *соответствующей информацией* ниже!"
      - "```🔗 Информация```"
      - "> Хост: `{host}`"
      - "> Тип: `{type}`"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
      - name: "📡 __**IP-адрес & Порт**__"
        value: "```{ip_address} | {port}```"
        inline: true
      - name: "🔗 __**Статус**__"
        value: "```🔴 Офлайн```"
        inline: true
  
  online-host: 
    title: "✅ Сервер включен"
    color: "custom"
    description: 
      - "> Мы **получили** результаты __анализа__."
      - "> Вы можете ознакомиться с *соответствующей информацией* ниже!"
      - "```🔗 Информация```"
      - "> Хост: `{host}:{port}`"
      - "> Тип: `{type}`"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
      - name: "📡 __**IP-адрес**__"
        value: "```{ip_address}```"
        inline: true
      - name: "🔗 __**Статус**__"
        value: "```🟢 Онлайн```"
        inline: true
      - name: "👤 __**Игроков**__"
        value: "```{players_online}/{players_max}```"
        inline: true
      - name: "📋 __**Motd**__"
        value: "```{motd}```"
        inline: true
  
  # Whois
  starting-checking: 
    title: "✅ Начальный домен запроса"
    color: "custom"
    description: 
      - "> Мы __отправили__ информацию, подлежащую **запросу**"
      - "> и ждем, когда *результаты будут отправлены обратно*!"
      - "> "
      - ">  Этот процесс может *занять некоторое время*! Пожалуйста подождите :("
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
      - name: "🌍 __**Домен**__"
        value: "```{domain}```"
        inline: true 
    
  invalid-domain: 
    title: ""
    color: "error"
    description: 
      - "> **Домен**, который вы ввели, сейчас недействителен!"
      - "> Не удается продолжить **извлечение** данных."
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: []
  
  invalid-query: 
    title: "❌ Неверный запрос для Домена"
    color: "custom"
    description: 
      - "> Мы **получили** результаты __запрошенного__."
      - "> Вы можете ознакомиться с *соответствующей информацией* ниже!"
      - "```🔗 Инфоормация```"
      - "> Домен: `{domain}`"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
      - name: "🔗 __**Статус**__"
        value: "```🔴 Неудача```"
        inline: true 
  
  query-success:  
    title: "✅ Успешный запрос домена"
    color: "custom"
    description: 
      - "> Мы **получили** результаты __запрошенного__."
      - "> Вы можете ознакомиться с *соответствующей информацией* ниже!"
      - "```🔗 Информация```"
      - "> Домен: `{domain}`"
      - "> Страна: `{country} [{country_code}]`"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
      - name: "📡 __**IP-адрес**__"
        value: "```{ip_address}```"
        inline: true
      - name: "🚦 __**AS**__"
        value: "```{as}```"
        inline: true
      - name: "📨 __**Интернет-провайдер**__"
        value: "```{isp}```"
        inline: true
      - name: "🚞 __**Город**__"
        value: "```{city} [{region_code}]```"
        inline: true
  
  # Update
  auto-update: 
    title: "✅ Автоматическое обновление прокси"
    color: "custom"
    description: 
      - "```🔗 Информация:```"
      - "> Обновлено: <@{client_id}>"
      - "> (`{client_id}`)"
      - "> Имя файла: `{file_name}`"
    thumbnail: ""
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Обновляется один раз каждые {update_time} минут!"
      icon: "{footer_icon}"
    fields: 
      - name: "🔧 __**Количество прокси:**__"
        value: "```{proxies} Прокси```"
        inline: true

  missing-url: 
    title: "❌ Пожалуйста, Введите URL-адрес"
    color: "error"
    description: 
      - "> Вы не полностью __заполнили__ **параметры**!"
      - "> Пожалуйста, введите URL-адрес для обновления *прокси*!"
      - "```📣 Информация```"
      - "> Вам нужно ввести __URL__ с правильным"
      - "> **форматом** и получите *результат*! Спасибо за понимание"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: []
  
  missing-config-url: 
    title: "❌ Введите URL-адрес в Конфигурации"
    color: "error"
    description: 
      - "> Вы не полностью __заполнили __ в **конфигурации**!"
      - "> Пожалуйста, введите URL-адрес *прокси*"
      - "> *обновить* в файле конфигурации!"
      - "```📢 Уведомление:```"
      - "> Вам нужно ввести __URL__ с правильным"
     - "> **форматом** и получите *результат*! Спасибо за понимание"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: []

  invalid-url: 
    title: "❌ Недопустимый URL-адрес прокси"
    color: "error"
    description: 
      - "> __URL__, который вы только что **ввели**, содержит"
      - "> *недопустимый формат*. Пожалуйста, проверьте еще раз!"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
      - name: "🚨 __**URL=ссылка**__"
        value: "[Только что введенный URL]({url})"
        inline: true
  
  loading-proxy: 
    title: "⏳ Получение информации о прокси"
    color: "custom"
    description: 
      - "> Мы __проводим__ тестирование, а также получаем"
      - "> данные **прокси**. Этот процесс может * занять некоторое время*!"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: []
  
  update-success: 
    title: "✅ Прокси успешно обновлены"
    color: "custom"
    description: 
      - "> Прокси были **успешно** обновлены. Ты можешь"
      - "> ознакомиться с __информацией__ об этом обновлении!"
      - "```🔗 Информация:```"
      - "> Имя файла: `{file_name}`"
    image: ""
    timeStamp: false
    author:
      name: ""
      icon: ""
      url: ""
    footer:
      text: "Для {user_tag}"
      icon: "{user_icon}"
    fields: 
      - name: "💥 __**Количество прокси:**__"
        value: "```{proxies} Прокси```"
        inline: true
